use-grammars = { only = [ "rust", "c", "cpp" ] }

[language-server.clangd]
config = { "fallbackFlags" = [ "-std=c23", "-Wall", "-pedantic" ] }

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "rust"
auto-format = false

[[language]]
name = "c"
indent = { unit = "\t", tab-width = 4 }
roots = [ ".git" ]

[[language]]
name = "cpp"
indent = { unit = "\t", tab-width = 4 }
roots = [ ".git" ]
