use-grammars = { only = [ "rust", "c", "cpp", "markdown" ] }

[language-server.discord-rpc]
command = "/home/lordgoatius/git/discord-rpc-lsp/discord-rpc-lsp"

[language-server.clangd]
config = { "fallbackFlags" = [ "-std=c23", "-Wall", "-pedantic" ] }

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "discord-rpc" ]
formatter = { command = "rustfmt" , args = ["+nightly"] }
auto-format = false
roots = [ ".git", "Cargo.toml" ]

[[language]]
name = "markdown"
language-servers = [ "marksman", "discord-rpc" ]

[[language]]
name = "c"
indent = { unit = "\t", tab-width = 4 }
roots = [ ".git" ]

[[language]]
name = "cpp"
indent = { unit = "\t", tab-width = 4 }
roots = [ ".git" ]

[[language]]
name = "python"
